title: "Javier Vicho Soto | AI & Data Science"
email: javiervicho@gmail.com
timezone: GMT
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo_small.png'
favicon: 'assets/images/favicon.ico'
author: Javier Vicho Soto
paginate: 30
disqus: 'demowebsite'
locale: en_gb
lang: en_gb
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  javier:
    name: Javier Vicho Soto
    display_name: Javier
    avatar: 'assets/images/javier.png'
    email: javiervicho@gmail.com
    web: https://javiervicho.github.io/
    linkedin: https://www.linkedin.com/in/javiervicho/
    description: "Data Scientist"

# Social
social:
  github: https://github.com/javiervicho
  linkedin: https://www.linkedin.com/in/javiervicho/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives